---
# tasks file for folding-at-home

- name: Install for CentOS
  include: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install for Debian
  include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Uninstall package
  package: name=fahclient state=absent
  when: state == 'absent'
  become: true

- name: Populate config.xml
  template: src=config.xml dest=/etc/fahclient/config.xml
  when: state == 'present'
  become: true
  notify: restart folding-at-home
